apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app-deployment
  labels:
    app: quote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
        - name: quote-app
          image: nithinmys/quote-app:v1   # build & push this image
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: quote-app-service
spec:
  selector:
    app: quote-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30091
  type: NodePort
